name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          # Use Node.js 18 LTS for Firebase functions compatibility
          node-version: 18
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install Functions dependencies
        run: npm ci --prefix functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DREAMANALYSIS_39322 }}
